### ISSUE TITLE
Keycloak 8.0.0 Support

### ISSUE THREAD

**Issue by Executioner1939** [fullfacing/keycloak4s#105]
Update Keycloak4s to support version 8.

**Comment by StuartJ45** [comment]
I created a [keycloak 8 feature branch](https://github.com/fullfacing/keycloak4s/tree/feature/keycloak8).
I'm not sure if we should just go forward with this version and drop future support for 7.0.1 and lower versions,
or keep separate branches for the different versions and update them individually.

**Comment by Executioner1939** [comment]
@StuartJ45 this depends on demand, currently I think bumping up to 8 would be okay. What we can do is branch and 7.X version from master and make master the branch that tracks the latest keycloak versions.

If we need to publish for older versions then we can setup jobs for the other branches

**Comment by StuartJ45** [comment]
@Executioner1939 Cool, I created a keycloak7 branch off develop and have now created a PR to merge the latest keycloak (8.0.1) changes into develop and master
