### ISSUE TITLE
Sttp module depends on Akka

### ISSUE THREAD

**Issue by Fristi** [fullfacing/keycloak4s#174]
When upgrading to 2.1.0 I noticed that it started to download Akka. Was working on a branch to resolve it, but weird issues regarding imports came up. Have you noticed this as well?

**Comment by StuartJ45** [comment]
It looks like we had akka unnecessarily as a dependency in the admin modules.
I've removed the dependency on a branch and will try get it released soon

**Comment by Executioner1939** [comment]
@Fristi please check the latest release. Thanks @StuartJ45 :-)
