### ISSUE TITLE
Update to support Keycloak 10.0.1

### ISSUE THREAD

**Issue by Executioner1939** [fullfacing/keycloak4s#197]
@StuartJ45 please can you update to support the above.

**Comment by StuartJ45** [comment]
From what I can tell, there have not been any changes to the rest admin API.
As usual, there is no change log for the admin API and I couldn't find any differences when comparing the [9.0](https://www.keycloak.org/docs-api/9.0/rest-api/index.html) and [10.0](https://www.keycloak.org/docs-api/10.0/rest-api/index.html) documentation pages
