### ISSUE TITLE
Using plain AkkaHttpBackend

### ISSUE THREAD

**Issue by BoopBoopBeepBoop** [fullfacing/keycloak4s#297]
First off thanks for putting this project up

I had a quick question: I was just attempting to wire this library to a plain sttp AkkaHttpBackend, and noticed that the `F[_]` type in core `KeycloakClient` appears to be more restrictive than the type returned from the AkkaHttpBackend. I'm not super well versed with cats-effect but my understanding is that the restriction to `Concurrent` makes it impossible to use plain scala Future, which is the `F[_]` associated with the AkkaHttpBackend.

Am I understanding correctly? Or do you know if there a way to provide evidence for `Concurrent[Future]` that I should use.

I can switch to the monix implementation if needed, just trying to determine if I'm understood correctly

**Comment by StuartJ45** [comment]
Hi, apologies for the late reply.

It seems the only way for scala's Future to work is by having an implicit instance of a new class that extends `Concurrent[Future]` in scope:
```scala
ConcurrentFuture extends Concurrent[Future] {
 //Implement all required methods
}
```
I believe the cats team did not include an implicit instance in their library due the fact that Future evaluates eagerly

**Comment by BoopBoopBeepBoop** [comment]
Great, thanks for confirming. That's what I figured after tracing through a number of PR's from cats. We're using the Akka/Monix backend now successfully (works great, we just had a few dependency conflicts I had to iron out).
