### ISSUE TITLE
Provide support for docker / proxy issuer validation

### ISSUE THREAD

**Issue by Cmancuso** [fullfacing/keycloak4s#313]
Having an issue getting a proxied request past the issuer validations provided by keycloak4s. 

When running a containerized instance of keycloak, the external host will differ from the host used inside the container. Upon validation of these issuers in keycloak4s, we'll return a 401 and an issuer validation error before the request is dispatched to Keycloak. Keycloak itself is equipped to handle this proxy via environment configurations, but the request is being blocked inside of the keycloak4s library as seen below.

![image](https://user-images.githubusercontent.com/6482567/108877509-4c132280-75cd-11eb-8580-ec14a54cbce3.png)

If there were an option to provide a valid redirect URL in the KeycloakConig object to be utilized here, or an option to bypass this validation, we should be able to proceed with the validation to keycloak successfully. 

If there is already a way to bypass this validation, please feel free to let me know. Thanks in advance.

**Comment by Executioner1939** [comment]
@Cmancuso sorry for the wait, @StuartJ45 has added this in and a release is running as we speak.
