### ISSUE TITLE
sttp v3 support

### ISSUE THREAD

**Issue by Voltir** [fullfacing/keycloak4s#379]
sttp has been on its v3 version for a bit of time now, and it would be nice for this keycloak api to support/publish using the v3 libraries, which are now published under, eg:

`com.softwaremill.sttp.client3`

**Comment by StuartJ45** [comment]
Thanks @Voltir!
I just need to also update our sttp backend [akkaMonixSttpBackend](https://github.com/fullfacing/akkaMonixSttpBackend) first, since the tests make use of it.
I will try get to that soon

**Comment by Voltir** [comment]
Great! Let me know if you want me to update my PR or if you guys want to roll out your update - we only depend on core and admin, so with a locally published fork I was able to continue testing on our side using the PR I opened.

**Comment by StuartJ45** [comment]
@Voltir Apologies for the delay, this has now been released
Struggled for a while with a json4s macros issue which was eventually solved by downgrading `enumeratum-json4s`

**Comment by Voltir** [comment]
Thanks again!
