### ISSUE TITLE
Allow admin-cli to authenticate with credentials

### ISSUE THREAD

**Issue by Fristi** [fullfacing/keycloak4s#53]
Hi!

Thanks for this great library, I was writing a client myself but this one is way more complete. I would be interested in contributing if there is overlap in our needs :-)

In my previous client I used credentials to authenticate with the master admin-cli client. The reason for that is because the importing of a realm-export can only be done to a new realm. So if you want to override settings for the master realm, you cannot do this automated (I couldn't find it atleast).

I think making `KeycloakConfig.Auth` an ADT which has two members `Secret` and `Credentials` which will be used in the `TokenManager` to exchange a token the way to go? What do you think?

Greets,

Mark

**Comment by lmuller90** [comment]
Hey Mark!

Appreciate the feedback, admittedly the methods we have of authenticating with the master admin-cli client is rather restrictive at the moment. Looking into expanding it with your suggestion in mind, will tag you into the PR when it's up so you can confirm if our solution suits your needs.

Regards,
Louis
