### ISSUE TITLE
Return UUID on `Users.create`

### ISSUE THREAD

**Issue by Fristi** [fullfacing/keycloak4s#57]
It can be extracted from header

**Comment by Fristi** [comment]
This is what I currently do in my client:

```scala
if (resp.status === Status.Created)
          resp.headers
            .get(CaseInsensitiveString("Location"))
            .map(redirectLocation => UUID.fromString(redirectLocation.value.split('/').last))
            .fold[F[Option[UUID]]](Sync[F].raiseError(new Throwable("No location header found")))(userId => Sync[F].pure(Option(userId)))
        else
          Sync[F].pure(Option.empty)
```

**Comment by Fristi** [comment]
Note that the side effects `.map` are not handled properly. It can happen that there is not a vaild `UUID` inside the header.

**Comment by lmuller90** [comment]
Looking into this right now, it's a bit tricky to implement due to how I've set up KeycloakClient, but a bit of restructuring should sort it out.
