### ISSUE TITLE
KeycloakSttpException should be logged as WARN?

### ISSUE THREAD

**Issue by Fristi** [fullfacing/keycloak4s#58]
Or atleast have the possibility to customize it, since creating a duplicate user results in a HTTP 409 - Conflict, which halts the process but is not a critical error

**Comment by Executioner1939** [comment]
@Fristi the 409 status code, being within the 400 range is indeed an error, semantically you attempted an operation that failed to complete. What scenario do you invision where this should be treated as a warning and not an error?

**Comment by Fristi** [comment]
If the user already exists, it will return a HTTP status code 409. I think it's not a system error, but just an error like bad request, not found, forbidden.. This is a user error, because the user doesn't know the intrinsic parts of the system it self

**Comment by Executioner1939** [comment]
@mark-dhl this is correct, it is not a system error (500 Range), but a Client / User Error (400 Range). I still feel that this should be propagated as an error in the application and not simply logged as a warning. 

If it were logged as a warning and returned succesfully the program would execute under the assumption that the operation was a success when in fact it wasn't. 

User code should guard against this, in your example a check to make sure a user doesn't already exist with a particular username should be implemented.
