### ISSUE TITLE
Authorizer for http4s

### ISSUE THREAD

**Issue by Fristi** [fullfacing/keycloak4s#59]
Would it be hard to extract the common parts from the akka http module to make a http4s module as well? 

I am not sure how the policy stuff works, but I have good knowledge on http4s.

**Comment by Executioner1939** [comment]
Hi @Fristi thanks for all the feedback, I am sure this would be possible, we currently only use akka-http however supporting http4s would be in the best interests of the community.

Both @lmuller90 and myself have little to no experience with http4s however and some help with this would be greatly appreciated.

**Comment by StuartJ45** [comment]
I should imagine it would not be too difficult.
I am looking into extracting all the common functionality out to make an http4s implementation module easy.

**Comment by lmuller90** [comment]
Just a heads up @StuartJ45 and myself will be refactoring the auth module to make it easier to add additional adapters, including splitting general functionality to an auth-core submodule that any adapter can make use of.

**Comment by Fristi** [comment]
Cool let me know when you extracted a common module which doesn't have the akka dependencies, then I'll start on http4s support :-)
