### ISSUE TITLE
Publish 1.2.3 for scala 2.12

### ISSUE THREAD

**Issue by Fristi** [fullfacing/keycloak4s#99]
I see sttp is being upgraded, I guess that's also in the release of 1.2.3 right? Would be great to have it, still on 2.12 for a bit

**Comment by Executioner1939** [comment]
@Fristi Hi, would you be able to help with this?

**Comment by Fristi** [comment]
How could I help? :) is the build not prepared for cross compiling? I can't publish I guess

**Comment by Executioner1939** [comment]
We don't know how to prepare the build for cross compiling, we haven't done it before. I can publish if we can get it cross compiling for all versions :-).
